# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "FFEditor"
license = "MIT"
description = "Theme based around a text interface and the Fairy Floss colorscheme"
tags = []
features = []
min_version = "0.166"

[author]
  name = "Kenneth Love"
  homepage = "https://thekennethlove.com"