baseURL = "https://thekennethlove.com/"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
enableRobotsTXT = true
languageCode = "en-us"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
sectionPagesMenu = "pagesMenu"
theme = "editor"
title = "Kenneth Love"

[author]
name = "Kenneth Love"

[permalinks]
posts = "/:year/:month/:title/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[menu.main]]
identifier = "readme"
name = "README.md"
url = "/"
weight = 100

[[menu.main]]
identifier = "mentoring"
name = "mentoring.md"
url = "/mentoring/"
weight = 110

[[menu.main]]
identifier = "social"
name = "social.md"
url = "/social/"
weight = 120

[[menu.main]]
identifier = "videos"
name = "videos.md"
url = "/videos/"
weight = 130

[[menu.main]]
identifier = "posts"
name = "posts/"
url = "/posts/"
weight = 140
